###

POST http://127.0.0.1:8000/api/auth/users/register HTTP/1.1
Content-Type: application/json
Accept: application/json

{
  "email": "saifs@gmail.com",
  "name": "Saif",
  "password": "12345678",
  "password_confirmation": "12345678"
}


###

POST http://127.0.0.1:8000/api/users/login HTTP/1.1
Content-Type: application/json
Accept: application/json

{
  "identifier": "saifss@gmail.com",
  "password": "12345678"
}
